---
title: "analyse_congestion"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{analyse_congestion}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(datatable.print.class = TRUE)
options(bitmapType='cairo')
```

```{r setup}
library(congestion)
library(xtradata)
library(sf)
library(ggplot2)
library(data.table)
library(dplyr)
```


```{r}
key <- Sys.getenv("XTRADATA_KEY")
typename <- "CI_TRAFI_L"
rangeStart <- "2021-11-01"
rangeEnd <- "2021-11-08"
```


# Dessin des tronçons

```{r}
troncons <- xtradata_requete_features(key = key, typename = typename, backintime = "2021-11-01T08:00:00")
```

```{r}
ggplot(troncons) +
  geom_sf(aes(color = "red")) +
  coord_sf() +
  theme_bw()
```



```{r}
sample_congestion

sample_congestion_week <- copy(sample_congestion) %>% 
  .[, .(score = mean(scores_horaires_ponderes, na.rm = TRUE)), by = gid]

troncons_scores <- inner_join(troncons, sample_congestion_week, by = "gid" )

```

# faire une carto, rajouter contours des communes etc ...
# faire un graphe joli

```{r}

congestion_gid <- copy(congestion_78weeks_dt) %>% 
  .[, .(score = mean(scores_horaires_ponderes, na.rm = TRUE)), by = gid]


troncons_scores <- inner_join(troncons, congestion_gid, by = "gid" )


ggplot(troncons_scores) +
  geom_sf(aes(color = score), lwd = 1) +
  coord_sf() +
  scale_color_gradient2(midpoint = median(troncons_scores$score, na.rm = TRUE), low = "#2E7F18",
                        mid = "yellow", high = "#C82538") +
  theme_bw()


```


# Time Series du niveau de congestion moyen

```{r}
congestion_from_sept2019_dt <- congestion_from_sept2019_dt %>% 
  .[, time := lubridate::as_datetime(time, tz = "Europe/Paris")] %>% 
  .[, date := lubridate::as_date(time)] %>% 
  .[, hour := data.table::hour(time)] %>% 
  .[, day := data.table::wday(time)] %>% 
  .[, HPM := hour %in% 7:9] %>% 
  .[, HPS := hour %in% 17:19] %>% 
  .[, JO := day %in% 2:6] %>% 
  .[scores_horaires_ponderes == 0, scores_horaires_ponderes := NA]



congestion_journaliere <- copy(congestion_from_sept2019_dt) %>% 
  .[, .(score = mean(scores_horaires_ponderes, na.rm = TRUE)), by = date]

```

```{r}
ggplot(congestion_journaliere, aes(x = date, y = score)) +
  geom_line() +
  geom_smooth()

# rajouter les confinements



congestion_journaliere[date=="2020-07-12"]
```


# En HPM, en HPS, en JO avec plusieurs panels



# Theme penguins à incorporer

```{r}
library(ggtext)

theme_set(theme_minimal(base_family = "Avenir Next Condensed"))
theme_update(
  axis.title = element_blank(),
  axis.text = element_text(color = "grey40"),
  axis.text.x = element_text(size = 20, margin = margin(t = 5)),
  axis.text.y = element_text(size = 17, margin = margin(r = 5)),
  axis.ticks = element_line(color = "grey91", size = .5),
  axis.ticks.length.x = unit(1.3, "lines"),
  axis.ticks.length.y = unit(.7, "lines"),
  panel.grid = element_blank(),
  plot.margin = margin(20, 40, 20, 40),
  plot.background = element_rect(fill = "grey98", color = "grey98"),
  panel.background = element_rect(fill = "grey98", color = "grey98"),
  plot.title = element_text(color = "grey10", size = 32, face = "bold",
                            margin = margin(t = 15)),
  plot.subtitle = element_markdown(color = "grey30", size = 17, 
                                   lineheight = 1.35,
                                   margin = margin(t = 15, b = 40)),
  plot.title.position = "plot",
  plot.caption.position = "plot",
  plot.caption = element_text(color = "grey30", size = 15,
                              lineheight = 1.2, hjust = 0, 
                              margin = margin(t = 40)),
  legend.position = "none"
)
```

```{r}
library(bdxmetroidentity)
library(ggtext)

confinements <- data.frame(
  deb = c(as.Date("2020-03-17"), as.Date("2020-10-30"), as.Date("2021-04-03")),
  fin = c(as.Date("2020-05-10"), as.Date("2020-12-14"), as.Date("2021-05-03")),
  label = c("Confinement", "Confinement", "Confinement")
)

mini <- min(congestion_journaliere$score)
maxi <- max(congestion_journaliere$score)

ggplot(congestion_journaliere, aes(x = date, y = score)) +
  geom_line(alpha = .7) +
  geom_smooth() +
  labs(x = "Date", y = "Score de congestion",
       title = "Temperatures in Chicago",
       subtitle = "Daily temperatures in °F from 1997 to 2001") +
  theme_bdxmetro_light() +
  theme(plot.title = element_text(family = "Bangers", hjust = .5, size = 25),
        plot.subtitle = element_text(family = "Playfair", hjust = .5, size = 15)) +
  
  # annotate("rect", data = confinements, aes(xmin = deb, xmax = fin, ymin = rep(-Inf, nrow(confinements)), ymax = rep(Inf, nrow(confinements))))
  
  annotate("rect", xmin = as.Date("2020-03-17"), xmax = as.Date("2020-05-10"), ymin = -Inf, ymax = Inf, alpha = .1, fill = "blue") +
  annotate("rect", xmin = as.Date("2020-10-30"), xmax = as.Date("2020-12-14"), ymin = -Inf, ymax = Inf, alpha = .1, fill = "blue") +
  annotate("rect", xmin = as.Date("2021-04-03"), xmax = as.Date("2021-05-03"), ymin = -Inf, ymax = Inf, alpha = .1, fill = "blue") +
  geom_vline(xintercept = as.numeric(as.Date("2021-06-20")), color = "red") +
  geom_richtext(data = confinements, mapping = aes(x = fin, y = 1.25, label = label), angle = 90,  hjust = 0,
                # nudge_y = -.01, nudge_x = -2,
                fill = NA, label.color = NA,
                label.padding = grid::unit(rep(1, 4), "lines")) +
  coord_cartesian( 
    # xlim = c(160, 250), 
    ylim = c(mini,maxi)
  )
# nudge_y = max(congestion_journaliere$score))

fill = NA, label.color = NA, # remove background and outline
label.padding = grid::unit(rep(0, 4), "pt") 


On pourrait annoter les points des confinements

p +
  annotate("rect", xmin = 1950, xmax = 1980, ymin = -1, ymax = 1,
           alpha = .1,fill = "blue")

# incorporer zone coloree confinement couvre feu etc ...
# https://dataviz.cerema.fr/trafic-routier/
# voir 2019/19 pour l'incorporation de fleches avec du texte : https://github.com/z3tt/TidyTuesday

```

```{r}
library(lubridate)
library(ggtext)

confinements <- data.frame(
  deb = c(as.Date("2020-03-17"), as.Date("2020-10-30"), as.Date("2021-04-03")),
  fin = c(as.Date("2020-05-10"), as.Date("2020-12-14"), as.Date("2021-05-03")),
  label = c("Confinement", "Confinement", "Confinement")
)

mini <- min(congestion_journaliere$score)
maxi <- max(congestion_journaliere$score)

ggplot(congestion_journaliere, aes(x = date, y = score)) +
  geom_line(alpha = .7) +
  geom_smooth(method = "gam") +
  labs(x = "Date", y = "Score de congestion",
       title = "Evolution score de confinement",
       subtitle = "Fluide (1) - Dense (2) - Embouteillé (3)") +
  # theme_bdxmetro_light() +
  theme(axis.title = element_blank(),
        # axis.text = element_text(color = "grey40"),
        # axis.text.x = element_text(size = 11),
        # axis.text.y = element_text(size = 11),
        # axis.ticks = element_line(color = "grey91", size = .5),
        # axis.ticks.length.x = unit(1.3, "lines"),
        # axis.ticks.length.y = unit(.7, "lines"),
        panel.grid = element_blank(),
        # plot.margin = margin(20, 40, 20, 40),
        plot.background = element_rect(fill = "grey98", color = "grey98"),
        panel.background = element_rect(fill = "grey98", color = "grey98"),
        plot.title = element_text(color = "grey10", size = 18),
        plot.subtitle = element_markdown(color = "grey30", size = 13),
        plot.title.position = "plot",
        plot.caption.position = "plot",
        # plot.caption = element_text(color = "grey30", size = 15,
        #                             lineheight = 1.2, hjust = 0, 
        #                             margin = margin(t = 40)),
        legend.position = "none") +
  
  annotate("rect", xmin = as.Date("2020-03-17"), xmax = as.Date("2020-05-10"), ymin = mini, ymax = maxi, alpha = .1, fill = "blue") +
  annotate("rect", xmin = as.Date("2020-10-30"), xmax = as.Date("2020-12-14"), ymin = mini, ymax = maxi, alpha = .1, fill = "blue") +
  annotate("rect", xmin = as.Date("2021-04-03"), xmax = as.Date("2021-05-03"),  ymin = mini, ymax = maxi, alpha = .1, fill = "blue") +
  annotate("segment", x = (as.Date("2021-06-20")), xend = (as.Date("2021-06-20")),  y = mini, yend = maxi,  color = "red") +
  
  geom_richtext(data = confinements, mapping = aes(x = fin - days(10), y = maxi, label = label), angle = -90, hjust = 0,
                fill = NA, label.color = NA) +
  # label.padding = grid::unit(rep(1, 4), "lines")) +
  coord_cartesian( 
    ylim = c(mini,maxi)
  )
```

# Autre theme 
```{r}
library(tidyverse)
library(ggrepel)
library(ggtext)
library(systemfonts)
library(gganimate)
```
```{r}
theme_set(theme_minimal(base_family = "Avenir Next Condensed"))
theme_update(
  axis.title = element_blank(),
  axis.text = element_text(color = "grey40"),
  axis.text.x = element_text(size = 20, margin = margin(t = 5)),
  axis.text.y = element_text(size = 17, margin = margin(r = 5)),
  axis.ticks = element_line(color = "grey91", size = .5),
  axis.ticks.length.x = unit(1.3, "lines"),
  axis.ticks.length.y = unit(.7, "lines"),
  panel.grid = element_blank(),
  plot.margin = margin(20, 40, 20, 40),
  plot.background = element_rect(fill = "grey98", color = "grey98"),
  panel.background = element_rect(fill = "grey98", color = "grey98"),
  plot.title = element_text(color = "grey10", size = 32, face = "bold",
                            margin = margin(t = 15)),
  plot.subtitle = element_markdown(color = "grey30", size = 17, 
                                   lineheight = 1.35,
                                   margin = margin(t = 15, b = 40)),
  plot.title.position = "plot",
  plot.caption.position = "plot",
  plot.caption = element_text(color = "grey30", size = 15,
                              lineheight = 1.2, hjust = 0, 
                              margin = margin(t = 40)),
  legend.position = "none"
)
```

```{r}
ggplot(congestion_journaliere, aes(x = date, y = score)) +
  geom_line(alpha = .7) +
  geom_smooth(method = "gam") +
  labs(x = "Date", y = "Score de congestion",
       title = "Evolution score de confinement",
       subtitle = "Fluide (1) - Dense (2) - Embouteillé (3)") +
  # theme_bdxmetro_light() +
  theme(plot.title = element_text(family = "Bangers", hjust = .5, size = 20),
        plot.subtitle = element_text(family = "Playfair", hjust = .5, size = 15)) +
  
  # annotate("rect", data = confinements, aes(xmin = deb, xmax = fin, ymin = rep(-Inf, nrow(confinements)), ymax = rep(Inf, nrow(confinements))))
  
  annotate("rect", xmin = as.Date("2020-03-17"), xmax = as.Date("2020-05-10"), ymin = mini, ymax = maxi, alpha = .1, fill = "blue") +
  annotate("rect", xmin = as.Date("2020-10-30"), xmax = as.Date("2020-12-14"), ymin = mini, ymax = maxi, alpha = .1, fill = "blue") +
  annotate("rect", xmin = as.Date("2021-04-03"), xmax = as.Date("2021-05-03"),  ymin = mini, ymax = maxi, alpha = .1, fill = "blue") +
  annotate("segment", x = (as.Date("2021-06-20")), xend = (as.Date("2021-06-20")),  y = mini, yend = maxi,  color = "red") +
  
  geom_richtext(data = confinements, mapping = aes(x = fin - days(10), y = maxi, label = label), angle = -90, hjust = 0,
                fill = NA, label.color = NA) +
  # label.padding = grid::unit(rep(1, 4), "lines")) +
  coord_cartesian( 
    ylim = c(mini,maxi)
  )
```


# Faire un GAM pour l'effet du confinement

# Carto animée

# Stream plot